version: '3.8'
services:
  db:
    image: postgres:15
    env_file: 
      - .db-env
    ports:
      - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .pgadmin-env
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: ./backend
    env_file:
      - .backend-env
    ports:
      - "4000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
