version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memodb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: still4steel
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: memodb

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
